### ISSUE TITLE
Loginmanager

### ISSUE THREAD

**Issue by killajoe** [endeavouros-team/EndeavourOS-archiso#13]
https://github.com/endeavouros-team/archiso-offlineinstaller/blob/190b82f7d192b50dc21f1092c5cb987fe0056023/run_before_squashfs.sh#L24

good to have this now at endeavouros-team!
For netinstaller ISO we need to remove setting to lightdm, as we do this per DE packages group post-install script:
https://github.com/endeavouros-team/install-scripts/blob/f7f3755001aca01c44ee6955d436b4856b0d5e59/cleaner_script.sh#L153

**Comment by Portergos** [comment]
Yes!
We need to organize the repos at github when we have more time.
I think we could merge scripts and live-desktop folders into one. Maybe others too.
As far as i see, the cleaner_script doesn't seem to work when using the online installer, not sure why. Need to investigate this.

**Comment by Portergos** [comment]
ok, o guess i just found out why it's not working, the function i created to detect which OS is running (endeavour, portergos, reborn) depends on /etc/os-release file (which is not installed with online option).
I'll add this to pacstrap module and test.
After this i can fix the login manager.

**Comment by Portergos** [comment]
DM problem is fixed using packages module.
