### ISSUE TITLE
Get a warning while starting a session: calamares_current not found in AUR.

### ISSUE THREAD

**Issue by FredBezies** [endeavouros-team/EndeavourOS-archiso#17]
Hello.

I know calamares_current will be remove soon, but with an installation using a git ISO based on 27th of august, I got this:

![VirtualBox_Parabola _28_08_2019_15_54_15](https://user-images.githubusercontent.com/8571419/63862163-6b1aff00-c9ac-11e9-851c-ce1da7c773d1.png)

Annoying. Will try to build another ISO with today's code and see if it still happens.

**Comment by Portergos** [comment]
https://forum.endeavouros.com/t/testing-endeavouros-devel-iso-calamares-remains-on-disk-after-install/1257

Reported and fixed already, closing.

Reopen in case you're still having the error.

**Comment by FredBezies** [comment]
No more kalu dialog. Thanks!
