### ISSUE TITLE
fix_permission.sh "shouting" about a missing file.

### ISSUE THREAD

**Issue by FredBezies** [endeavouros-team/EndeavourOS-archiso#19]
Looks like fix_permission.sh needs a little tweak. See screenshot:

![VirtualBox_EndeavourOS - build_01_10_2019_10_56_54](https://user-images.githubusercontent.com/8571419/65948388-70032080-e43a-11e9-9556-3b310210d694.png)

Related to this commit, I think. https://github.com/endeavouros-team/EndeavourOS-archiso/commit/324b61e4cea397fa8c555d0b79a07f0463aac714

@Portergos : what about modifying this line in fix_permission.sh?

```
chmod +x ./{build.sh,mkarchiso,run_before_squashfs.sh,inject_repo.sh}
```
by:

```
chmod +x ./{build.sh,mkarchiso,run_before_squashfs.sh}
```

Just guessing of course :)

**Comment by Portergos** [comment]
Thanks for reporting! Fixed!
