### ISSUE TITLE
multi WM Live iso ?

### ISSUE THREAD

**Issue by 1000i100** [endeavouros-team/EndeavourOS-archiso#31]
Hi, on your website, you say endavourOS give choice between 8 WM.
Could i test them with the liveCD/DVD/USB ?
If not, is-it planned and/or is there other live distro with this feature ?

**Comment by killajoe** [comment]
8 Window Managers? LiveISO only has xfce4 as Desktop Environment. 
You can choose different DM's for the install and since the last update also i3wm.
