### ISSUE TITLE
Remove either neofetch or screenfetch.

### ISSUE THREAD

**Issue by FredBezies** [endeavouros-team/EndeavourOS-archiso#33]
In both offline and online packages.conf there is both screenfetch and neofetch.

I think removing one is a good idea :)

**Comment by killajoe** [comment]
`sudo pacman -S screenfetch neofetch
resolving dependencies...
looking for conflicting packages...

Packages (2) neofetch-7.0.0-1  screenfetch-3.9.1-1

Total Download Size:   0,13 MiB
Total Installed Size:  0,55 MiB
`

**Comment by FredBezies** [comment]
I know they're very light. But do we need both ?

**Comment by FredBezies** [comment]
Let's keep both. It won't hurt. Closing this bug.
