### ISSUE TITLE
Error installing bootloader

### ISSUE THREAD

**Issue by krateng** [endeavouros-team/EndeavourOS-archiso#35]
I'm having some troubles installing, I hope someone can tell me what's wrong from this.

While the OS itself installs correctly, I get this problem at the end:

```
Boost.Python error in job "bootloader".
Command 'grub-install --target=x86_64-efi --efi-directory=/boot/efi --bootloader-id=EndeavourOS --force' returned non-zero exit status 1.
Installing for x86_64-efi platform. Could not prepare Boot variable: Input/output error grub-install: error: efibootmgr failed to register the boot entry: Input/output error.

Traceback:
File "/usr/lib/calamares/modules/bootloader/main.py", line 485, in run
    prepare_bootloader(fw_type)

  File "/usr/lib/calamares/modules/bootloader/main.py", line 457, in prepare_bootloader
    install_grub(efi_directory, fw_type)

  File "/usr/lib/calamares/modules/bootloader/main.py", line 319, in install_grub
    check_target_env_call([libcalamares.job.configuration["grubInstall"],

  File "<string>", line 6, in <module>
```

Using endeavouros-2020.07.15-x86_64, no custom partitioning. I've previously had Solus OS on it and it booted without problems.

Thanks!

**Comment by killajoe** [comment]
could you go with this to the Forum? GitHub is only for development, Bugs, and issues on install should are reported on the forum. 

_`no custom partitioning`_ so could be some irritation on before existing partitions (kpm-core is sensitive to this) i would try to remove partitions before install, you can use gparted on the ISO for this before starting installer simple create a new partitonsheme no need to setup partitions (gpt for EFI systems ;) )

**Comment by krateng** [comment]
> GitHub is only for development, Bugs, and issues on install should are reported on the forum

Apologies, wasn't aware of that, I'll post it there.
