### ISSUE TITLE
Keyboard and touchpad not working on ASUS K556UQ laptop

### ISSUE THREAD

**Issue by Juampa852** [endeavouros-team/EndeavourOS-archiso#38]
Hi!, I had EndeavourOS installed, on Aug 16 I update the system (yay -Suy) and restart, when I enter to my PC again, the keyboard and touchpad wasn't working, but I had an USB mouse and keyboard and they works fine. I installed the "xf86-input-synaptics" package and that fixed the touchpad issue, but the "xf86-input-keyboard" package is no longer in the Arch repos.

A few days ago, I reinstalled EndeavourOS, on the live installer everything works fine, but at the first boot from the installation, my keyboard and touchpad wasn't working again.

I have an ASUS K556UQ laptop, here's an "hwinfo --short" output, taken in KDE Neon (because I can't do nothing on EndeavourOS):
cpu:                                                            
                       Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz, 1128 MHz
                       Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz, 1155 MHz
                       Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz, 1156 MHz
                       Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz, 1150 MHz
keyboard:
  /dev/input/event4    AT Translated Set 2 keyboard
mouse:
  /dev/input/mice      Asus TouchPad
monitor:
                       AUO LCD Monitor
graphics card:
                       nVidia GM108M [GeForce 940MX]
                       Intel HD Graphics 620
sound:
                       Intel Sunrise Point-LP HD Audio
storage:
                       Intel Sunrise Point-LP SATA Controller [AHCI mode]
network:
  wlp3s0               Qualcomm Atheros QCA9565 / AR9565 Wireless Network Adapter
  enp2s0               Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller
network interface:
  enp2s0               Ethernet network interface
  lo                   Loopback network interface
  wlp3s0               Ethernet network interface
disk:
  /dev/sda             TOSHIBA MQ01ABD1
partition:
  /dev/sda1            Partition
  /dev/sda2            Partition
  /dev/sda3            Partition
  /dev/sda4            Partition
  /dev/sda5            Partition
  /dev/sda6            Partition
  /dev/sda7            Partition
cdrom:
  /dev/sr0             HL-DT-ST DVDRAM GUE1N
usb controller:
                       Intel Sunrise Point-LP USB 3.0 xHCI Controller
bios:
                       BIOS
bridge:
                       Intel Sunrise Point-LP PCI Express Root Port #1
                       Intel Sunrise Point-LP LPC Controller
                       Intel Sunrise Point-LP PCI Express Root Port #6
                       Intel Xeon E3-1200 v6/7th Gen Core Processor Host Bridge/DRAM Registers
                       Intel Sunrise Point-LP PCI Express Root Port #5
hub:
                       Linux Foundation 2.0 root hub
                       Linux Foundation 3.0 root hub
memory:
                       Main Memory
bluetooth:
                       Lite-On Bluetooth Device
unknown:
                       FPU
                       DMA controller
                       PIC
                       Keyboard controller
                       PS/2 Controller
                       Intel Sunrise Point-LP PMC
                       Intel Sunrise Point-LP Serial IO I2C Controller #1
                       Intel Xeon E3-1200 v5/E3-1500 v5/6th Gen Core Processor Thermal Subsystem
                       Intel Sunrise Point-LP CSME HECI #1
                       Intel Sunrise Point-LP Serial IO I2C Controller #0
                       Intel Sunrise Point-LP Thermal subsystem
                       Intel Sunrise Point-LP SMBus
  /dev/input/event10   IMC Networks USB2.0 VGA UVC WebCam
                       Realtek RTS5129 Card Reader Controller

**Comment by killajoe** [comment]
As this is not specific to the installer or the ISO, I would like you to post this on the forum.
There you can get help from all 10.000 logged in users:
https://forum.endeavouros.com
