### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by LexxFade** [endeavouros-team/EndeavourOS-archiso#42]
![6be94bef-357d-48f8-9092-3730d0256ff5](https://user-images.githubusercontent.com/74601193/101884577-fd4b1480-3ba9-11eb-8464-40906d94607a.jpg)

**Comment by killajoe** [comment]
It looks like a KPM issue with existing partitions.
If you install EndeavourOS as the only OS I would recommend cleaning the drive before starting the installation, in some cases, KPMcore is sensitive to changes on the partitions done before it starts handling it. 
Usually we do handle BUGS/issues on the Forum, please ask there if you want to get help by all community and not only ba some devs mostlikely do not see this here ;) https://forum.endeavouros.com/
